aws:
  # What AWS region do we use for VPC and ASG stacks?
  # optional
  region: us-east-1
  # What is the AMI ID of the Folding @ Home Image
  # mandatory
  ami_id: ami-1234567890
  # What ssh key is allowed access to the instances in the ASG?
  # mandatory
  ssh_key: super-private-ssh-key
  # What is the maximum price in USD that we're willing to pay?
  # If you leave this empty, we will fetch the current spot price
  # and raise the bid by a few cents. The instances will be set up
  # only after confirmation
  # optional
  max_spot_price: ""
  # What IP addresses to allow security group access from?
  # mandatory
  ssh_allow_ip_range: 192.168.0.1/32
  # What instance type/sizing would you prefer?
  # optional
  ec2_instance_type: "c5n.large"
  # How many instances do you wish to use?
  # optional
  asg_size: 2
