example-name:
  # What AWS region do we use for VPC and ASG stacks?
  # optional
  region: us-east-1
  # What is the AMI ID of the Folding @ Home Image
  # mandatory
  ami_id: ami-1234567890
  # What ssh key is allowed access to the instances in the ASG?
  # mandatory
  ssh_key: super-private-ssh-key
  # What is the maximum price in USD that we're willing to pay?
  # mandatory
  max_spot_price: "1.234"
  # What IP addresses to allow security group access from?
  # mandatory
  ssh_allow_ip_range: 192.168.0.1/32
  # What instance type/sizing would you prefer?
  # optional
  ec2_instance_type: "c5n.large"
  # How many instances do you wish to use?
  # optional
  asg_size: 2
  # cidr of the VPC
  cidr: 10.0.0.0/16
